version: '3.8'
services:
  app:
    build: .
    container_name: symfony_app
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8081}:8081"
    depends_on:
      - manticore
    # volumes:
    #   - ./:/var/www/html
    working_dir: /var/www/html
  manticore:
    image: manticoresearch/manticore:latest
    container_name: manticore_search
    ports:
      - "9306:9306"
      - "9308:9308"
    volumes:
      - manticore_data:/var/lib/manticore
volumes:
  manticore_data:
